services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-notex
    environment:
      - 'POSTGRES_DB=notex'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=notex_user'
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin12345
    volumes:
      - ./minio-data:/data