services:
  postgres:
    image: postgres:17
    container_name: postgres-notex-backend
    environment:
      POSTGRES_DB: notex
      POSTGRES_USER: notex_user
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    networks:
      - notex-network

  minio:
    image: minio/minio:latest
    container_name: minio-backend
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../minio-data:/data
    networks:
      - notex-network

  backend:
    container_name: backend-notex-standalone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DATABASE_URL: jdbc:postgresql://postgres:5432/notex
      DATABASE_USERNAME: notex_user
      DATABASE_PASSWORD: secret
      MINIO_URL: http://minio:9000
      MINIO_PUBLIC_URL: http://localhost:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin12345
    env_file:
      - ../.env
    depends_on:
      - postgres
      - minio
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - notex-network

networks:
  notex-network:
    driver: bridge
